### ISSUE TITLE
Cell: new states

### ISSUE THREAD

**Issue by dukeOfPrunes** [hotgloupi/angry-ball#1]
solid: same behavior as the borders
speed up/down or change friction
+x: constrain movement in +x
-x: constrain movement in -x
+y: constrain movement in +y
-y: constrain movement in -y
spread: cell affects adjacent cells

more to come

**Comment by hotgloupi** [comment]
Could you make one per kind of cell ? So that we can implement/discuss each one separately ?

**Comment by hotgloupi** [comment]
Closing in favor of #11
