### ISSUE TITLE
Event sounds

### ISSUE THREAD

**Issue by dukeOfPrunes** [hotgloupi/angry-ball#8]
Do we need sound fx?

**Comment by hotgloupi** [comment]
I would say that In-game sounds are required, and in general, each event (player moving, mouse/touch screen, board events) should be able to generate a sound.

**Comment by aletord** [comment]
i should be able to find what we need if we know what we need exactly, i need more informations about the composition of each events and what they exacty done.

**Comment by hotgloupi** [comment]
@aletord You're right, I'll close this issue in favor of #13 and #12, where we can describe precisely what we want to try
